"""Generate a docker-compose.twin.yml for local digital-twin testing.

The twin runs the full stack on the developer's machine (typically amd64),
replacing platform-specific images where needed and mocking hardware
dependencies (display, I2C, GPIO) via environment variables and stub
containers.

Usage::

    from redeploy.blueprint.generators.docker_compose import generate_twin
    compose_yaml = generate_twin(blueprint)
"""
from __future__ import annotations

import re
from typing import Any

import yaml

from ...models import DeviceBlueprint, ServiceSpec

# ── Platform remap table ───────────────────────────────────────────────────────
# If the original image has no known amd64 variant we annotate it.
_ARM_ONLY_PREFIXES = ("balena/", "resin/", "raspberrypi")


def generate_twin(
    blueprint: DeviceBlueprint,
    *,
    local_platform: str = "linux/amd64",
    port_offset: int = 0,
    network_name: str = "twin",
    compose_version: str = "3.8",
    add_mock_display: bool = True,
    env_overrides: dict[str, str] | None = None,
) -> str:
    """Render a docker-compose YAML string for a local digital-twin.

    Parameters
    ----------
    blueprint:
        Source DeviceBlueprint extracted from the real device.
    local_platform:
        Target platform for the twin (default ``linux/amd64``).
    port_offset:
        Add this offset to all host ports to avoid conflicts, e.g. ``10000``.
    network_name:
        Docker network name for the twin stack.
    add_mock_display:
        If the blueprint requires a DSI display, inject a headless Xvfb
        stub so the UI container has a framebuffer to connect to.
    env_overrides:
        Extra env vars to inject into every service (e.g. ``TWIN=1``).
    """
    services: dict[str, Any] = {}

    for svc in blueprint.services:
        svc_def = _build_service(
            svc,
            local_platform=local_platform,
            port_offset=port_offset,
            env_overrides=env_overrides or {},
            twin_network=network_name,
        )
        services[svc.name] = svc_def

    # Mock display stub
    if add_mock_display and blueprint.hardware.display_type in ("DSI", "HDMI"):
        res = blueprint.hardware.display_resolution or "1280x800"
        w, _, h = res.partition("x")
        services["_mock_display"] = {
            "image": "jlesage/xvfb:latest",
            "platform": local_platform,
            "environment": {
                "DISPLAY_WIDTH": w or "1280",
                "DISPLAY_HEIGHT": h or "800",
                "DISPLAY": ":99",
            },
            "networks": [network_name],
            "profiles": ["mock"],         # only started with --profile mock
            "labels": {"twin.role": "mock-display"},
        }

    # Compose document
    doc: dict[str, Any] = {
        "# Generated by redeploy blueprint twin": None,
        "# Source blueprint": blueprint.name,
        "# Original device": blueprint.source.device_id or "unknown",
    }

    compose: dict[str, Any] = {
        "version": compose_version,
        "services": services,
        "networks": {
            network_name: {"driver": "bridge"},
        },
    }

    # Render: comments first (not directly supported by yaml.dump — use a header)
    header = (
        f"# Generated by redeploy blueprint twin\n"
        f"# Source blueprint : {blueprint.name} v{blueprint.version}\n"
        f"# Original device  : {blueprint.source.device_id or 'unknown'}\n"
        f"# Original platform: {blueprint.hardware.arch or 'unknown'}\n"
        f"# Twin platform    : {local_platform}\n"
        f"#\n"
        f"# Start with:  docker compose -f docker-compose.twin.yml up\n"
        f"# With mocks:  docker compose -f docker-compose.twin.yml --profile mock up\n\n"
    )
    body = yaml.dump(compose, allow_unicode=True, sort_keys=False, default_flow_style=False)
    return header + body


def _build_service(
    svc: ServiceSpec,
    *,
    local_platform: str,
    port_offset: int,
    env_overrides: dict[str, str],
    twin_network: str,
) -> dict[str, Any]:
    d: dict[str, Any] = {}

    # Image — keep original; add platform override
    d["image"] = svc.image or "scratch"
    if local_platform:
        d["platform"] = local_platform

    # Ports — apply offset if non-zero
    if svc.ports:
        port_list = []
        for p in svc.ports:
            host_port = p.host + port_offset
            entry = f"{host_port}:{p.container}"
            if p.protocol != "tcp":
                entry += f"/{p.protocol}"
            port_list.append(entry)
        d["ports"] = port_list

    # Volumes — swap absolute host paths to named volumes for portability
    if svc.volumes:
        vols = []
        named: dict[str, Any] = {}
        for v in svc.volumes:
            if v.host.startswith("/"):
                vol_name = re.sub(r"[^a-zA-Z0-9_]", "_", v.host.strip("/")) or "data"
                vols.append(f"{vol_name}:{v.container}" + (":ro" if v.read_only else ""))
                named[vol_name] = {"driver": "local"}
            else:
                vols.append(f"{v.host}:{v.container}" + (":ro" if v.read_only else ""))
        d["volumes"] = vols
        if named:
            d["_named_volumes"] = named   # caller merges into top-level volumes

    # Environment — original + twin overrides
    env = dict(svc.env)
    env["TWIN"] = "1"
    env["DIGITAL_TWIN_SOURCE"] = svc.source_ref or "blueprint"
    env.update(env_overrides)
    # Redact secrets for display (keep them for actual use)
    if env:
        d["environment"] = env

    # Hardware stubs — replace real device paths with no-ops
    if svc.privileged:
        # drop privilege in twin — could break some things, user can override
        d["# privileged"] = "true (removed in twin — re-add if needed)"
    else:
        d["privileged"] = False

    if svc.command:
        d["command"] = svc.command

    if svc.restart:
        d["restart"] = svc.restart

    if svc.depends_on:
        d["depends_on"] = svc.depends_on

    d["networks"] = [twin_network]

    if svc.healthcheck:
        d["healthcheck"] = {
            "test": ["CMD-SHELL", svc.healthcheck],
            "interval": "10s",
            "timeout": "5s",
            "retries": 3,
        }

    return d
