"""DetectionWorkflow — multi-host orchestrated detection with template matching.

The workflow runs these stages in order::

    Stage 0: Collect hosts
        sources: spec.source.host, redeploy.yaml environments, device registry,
                 auto_probe of unknown IPs
    Stage 1: SSH probe (auto_probe) — credentials + arch + strategy hint
    Stage 2: Deep detect (Detector.run) — ports, services, conflicts, health
    Stage 3: Template scoring (TemplateEngine) — rank templates per host
    Stage 4: Environment classification — map host → env label
    Stage 5: Report + generate — redeploy.yaml snippet + spec template suggestion

Each stage is logged and produces a ``WorkflowStageResult`` so the user can
inspect intermediate state.  The full output is a ``WorkflowResult``.

Usage (CLI)::

    redeploy detect --workflow --hosts 192.168.188.108 87.106.87.183
    redeploy detect --workflow --scan 192.168.188.0/24
    redeploy detect --workflow   # reads hosts from redeploy.yaml + registry

Usage (Python)::

    from redeploy.detect.workflow import DetectionWorkflow
    result = DetectionWorkflow().run(hosts=["192.168.188.108"])
    print(result.summary())
    print(result.generated_redeploy_yaml())
"""
from __future__ import annotations

import textwrap
from dataclasses import dataclass, field
from typing import Optional

from loguru import logger

from ..models import DeployStrategy, DeviceRegistry, InfraState, ProjectManifest
from .detector import Detector
from .templates import DetectionResult, TemplateEngine, build_context


# ── Per-host result ───────────────────────────────────────────────────────────

@dataclass
class HostDetectionResult:
    """Full detection result for a single host."""
    host: str                           # user@ip or ip
    ip: str = ""
    reachable: bool = False
    ssh_user: str = ""
    ssh_key: str = ""
    arch: str = ""
    os_info: str = ""

    state: Optional[InfraState] = None
    template_result: Optional[DetectionResult] = None

    error: str = ""

    @property
    def strategy(self) -> DeployStrategy:
        if self.template_result:
            return self.template_result.strategy
        if self.state:
            return self.state.detected_strategy
        return DeployStrategy.UNKNOWN

    @property
    def environment(self) -> str:
        return self.template_result.environment if self.template_result else "unknown"

    @property
    def confidence(self) -> str:
        return self.template_result.best.confidence_label if self.template_result else "—"

    @property
    def template_name(self) -> str:
        return self.template_result.best.template.name if self.template_result else "—"

    @property
    def spec_template(self) -> str:
        return self.template_result.spec_template if self.template_result else ""

    def env_block(self) -> str:
        if self.template_result:
            return self.template_result.generated_env_block(host=self.host)
        return ""

    def notes(self) -> list[str]:
        return self.template_result.generated_notes() if self.template_result else []


# ── Workflow result ───────────────────────────────────────────────────────────

@dataclass
class WorkflowResult:
    """Aggregated result across all probed hosts."""
    hosts: list[HostDetectionResult] = field(default_factory=list)
    app: str = "app"

    @property
    def reachable(self) -> list[HostDetectionResult]:
        return [h for h in self.hosts if h.reachable]

    @property
    def unreachable(self) -> list[HostDetectionResult]:
        return [h for h in self.hosts if not h.reachable]

    def by_env(self) -> dict[str, list[HostDetectionResult]]:
        result: dict[str, list[HostDetectionResult]] = {}
        for h in self.reachable:
            result.setdefault(h.environment, []).append(h)
        return result

    def summary(self) -> str:
        lines = [f"DetectionWorkflow: {len(self.reachable)}/{len(self.hosts)} reachable"]
        for h in self.hosts:
            status = "✓" if h.reachable else "✗"
            tpl = h.template_name[:40] if h.reachable else h.error[:40]
            lines.append(
                f"  {status} {h.host:<28}  env={h.environment:<10}  "
                f"strategy={h.strategy.value:<16}  conf={h.confidence:<6}  "
                f"{tpl}"
            )
        return "\n".join(lines)

    def generated_redeploy_yaml(self) -> str:
        """Generate a complete redeploy.yaml with all detected environments."""
        lines = [
            f"# redeploy.yaml — auto-generated by `redeploy detect --workflow`",
            f"app: {self.app}",
            f"spec: migration.yaml",
            f"",
            f"environments:",
        ]
        seen_envs: set[str] = set()
        for h in self.reachable:
            env = h.environment
            # Make env name unique if same env label for multiple hosts
            env_key = env
            suffix = 2
            while env_key in seen_envs:
                env_key = f"{env}{suffix}"
                suffix += 1
            seen_envs.add(env_key)

            ip = h.ip or (h.host.split("@")[-1] if "@" in h.host else h.host)
            port = 8000
            if h.state and 8100 in h.state.ports:
                port = 8100
            elif h.state and 8080 in h.state.ports:
                port = 8080

            lines += [f"  {env_key}:"]
            lines += [f"    host: {h.host}"]
            lines += [f"    strategy: {h.strategy.value}"]
            if h.ssh_key:
                lines += [f"    ssh_key: {h.ssh_key}"]
            if h.state and h.state.current_version:
                lines += [f"    # detected version: {h.state.current_version}"]
            lines += [f"    verify_url: http://{ip}:{port}/api/v1/health"]
            lines += [f"    # template: {h.spec_template}"]
            for note in h.notes():
                lines += [f"    # {note}"]
            lines += [f""]
        return "\n".join(lines)

    def generated_migration_yaml(self, env: str = "") -> str:
        """Generate a migration.yaml skeleton for the given env (or best match)."""
        host_res = next(
            (h for h in self.reachable if h.environment == env),
            self.reachable[0] if self.reachable else None,
        )
        if not host_res:
            return "# No reachable hosts detected"

        app = self.app
        strategy = host_res.strategy.value
        h = host_res.host
        ip = host_res.ip or (h.split("@")[-1] if "@" in h else h)
        ver = (host_res.state.current_version or "?") if host_res.state else "?"

        return textwrap.dedent(f"""\
            # migration.yaml — auto-generated by `redeploy detect --workflow`
            # Template: {host_res.spec_template}
            name: "{app} {strategy} — {ver} → NEW_VERSION"
            description: "Deploy {app} to {h}"

            source:
              strategy: {strategy}
              host: {h}
              app: {app}
              version: "{ver}"
              domain: "{ip}"

            target:
              strategy: {strategy}
              host: {h}
              app: {app}
              version: "NEW_VERSION"
              domain: "{ip}"
              verify_url: http://{ip}:8000/api/v1/health
              verify_version: "NEW_VERSION"

            extra_steps: []

            notes:
            """)


# ── Workflow orchestrator ─────────────────────────────────────────────────────

class DetectionWorkflow:
    """Multi-host detection workflow with template scoring.

    Stages::

        0. collect_hosts  — from args, redeploy.yaml, registry, scan
        1. probe_ssh      — auto_probe each host (credentials + quick info)
        2. deep_detect    — Detector.run (ports, services, health, conflicts)
        3. score_template — TemplateEngine.detect per host
        4. classify_env   — map → environment label
        5. generate       — redeploy.yaml + migration.yaml snippets

    Args:
        templates:   Override built-in template list (for testing/extension).
        deep:        If False, skip stage 2 (SSH probe only, faster but less accurate).
        timeout:     SSH timeout per host.
    """

    def __init__(
        self,
        templates=None,
        deep: bool = True,
        timeout: int = 8,
    ):
        self.engine = TemplateEngine(templates)
        self.deep = deep
        self.timeout = timeout

    # ── Stage 0: collect hosts ────────────────────────────────────────────────

    def _collect_hosts(
        self,
        hosts: list[str],
        manifest: Optional[ProjectManifest],
        registry: Optional[DeviceRegistry],
        scan_subnet: Optional[str],
    ) -> list[str]:
        """Merge host sources into deduplicated list."""
        from pathlib import Path
        collected: list[str] = list(hosts)

        # From redeploy.yaml environments
        if manifest:
            for env_name, env_cfg in manifest.environments.items():
                if env_cfg.host and env_cfg.host not in ("local", "localhost") \
                   and env_cfg.host not in collected:
                    collected.append(env_cfg.host)
                    logger.debug(f"[workflow] host from manifest env '{env_name}': {env_cfg.host}")

        # From device registry
        if registry:
            for dev in registry.devices:
                if dev.host and dev.host not in collected \
                   and dev.host not in ("local", "localhost"):
                    collected.append(dev.host)
                    logger.debug(f"[workflow] host from registry '{dev.id}': {dev.host}")

        # Optional subnet scan
        if scan_subnet:
            from ..discovery import discover
            logger.info(f"[workflow] scanning subnet {scan_subnet}...")
            found = discover(subnet=scan_subnet, ping=True, mdns=False,
                             probe_ssh=False, timeout=3)
            for h in found:
                if h.ip and h.ip not in collected:
                    collected.append(h.ip)
                    logger.debug(f"[workflow] host from scan: {h.ip}")

        # Deduplicate preserving order
        seen: set[str] = set()
        result: list[str] = []
        for h in collected:
            key = h.split("@")[-1] if "@" in h else h   # deduplicate by IP
            if key not in seen:
                seen.add(key)
                result.append(h)

        return result

    # ── Stage 1: SSH probe ────────────────────────────────────────────────────

    def _probe_ssh(self, host: str) -> HostDetectionResult:
        from ..discovery import auto_probe
        res = HostDetectionResult(host=host)
        try:
            p = auto_probe(host, timeout=self.timeout, save=True)
            res.reachable = p.reachable
            res.ip = p.ip
            res.ssh_user = p.ssh_user
            res.ssh_key = p.ssh_key
            res.arch = p.arch
            res.os_info = p.os_info
            if not p.reachable:
                res.error = p.error
        except Exception as e:
            res.error = str(e)
        return res

    # ── Stage 2: deep detect ──────────────────────────────────────────────────

    def _deep_detect(self, res: HostDetectionResult) -> HostDetectionResult:
        try:
            host_str = res.host if "@" in res.host else f"{res.ssh_user}@{res.ip}" if res.ssh_user else res.host
            d = Detector(host=host_str, app="")
            if res.ssh_key:
                d.probe.key = res.ssh_key
            state = d.run()
            res.state = state
        except Exception as e:
            logger.warning(f"[workflow] deep detect failed for {res.host}: {e}")
        return res

    # ── Stage 3: template scoring ─────────────────────────────────────────────

    def _score_template(
        self,
        res: HostDetectionResult,
        manifest: Optional[ProjectManifest],
    ) -> HostDetectionResult:
        from ..discovery import ProbeResult
        # Build a minimal ProbeResult for context even if deep detect was skipped
        probe_mock = ProbeResult(
            ip=res.ip,
            host=res.host,
            ssh_user=res.ssh_user,
            ssh_key=res.ssh_key,
            arch=res.arch,
            os_info=res.os_info,
            reachable=res.reachable,
        )
        state = res.state
        if state is None:
            # Build minimal InfraState from probe data so template engine can run
            from ..models import InfraState, RuntimeInfo
            state = InfraState(
                host=res.host,
                app="",
                runtime=RuntimeInfo(arch=res.arch, os=res.os_info),
                detected_strategy=DeployStrategy.UNKNOWN,
            )

        tr = self.engine.detect(state, probe=probe_mock, manifest=manifest)
        res.template_result = tr
        return res

    # ── Public: run ───────────────────────────────────────────────────────────

    def run(
        self,
        hosts: Optional[list[str]] = None,
        manifest: Optional[ProjectManifest] = None,
        registry: Optional[DeviceRegistry] = None,
        scan_subnet: Optional[str] = None,
        app: str = "app",
    ) -> WorkflowResult:
        """Execute all stages. Returns WorkflowResult."""
        result = WorkflowResult(app=app)

        # Stage 0: collect
        all_hosts = self._collect_hosts(
            hosts or [],
            manifest,
            registry or DeviceRegistry.load(),
            scan_subnet,
        )
        if not all_hosts:
            logger.warning("[workflow] no hosts to probe")
            return result

        logger.info(f"[workflow] {len(all_hosts)} host(s) to probe: {all_hosts}")

        for host in all_hosts:
            logger.info(f"[workflow] → {host}")

            # Stage 1: SSH probe
            host_res = self._probe_ssh(host)
            if not host_res.reachable:
                logger.warning(f"[workflow]   ✗ unreachable: {host_res.error}")
                result.hosts.append(host_res)
                continue
            logger.info(f"[workflow]   ✓ SSH OK ({host_res.ssh_user}  arch={host_res.arch})")

            # Stage 2: deep detect (optional)
            if self.deep:
                host_res = self._deep_detect(host_res)
                if host_res.state:
                    logger.info(
                        f"[workflow]   strategy={host_res.state.detected_strategy}  "
                        f"ports={sorted(host_res.state.ports.keys())}  "
                        f"conflicts={len(host_res.state.conflicts)}"
                    )

            # Stage 3: template scoring
            host_res = self._score_template(host_res, manifest)
            if host_res.template_result:
                best = host_res.template_result.best
                logger.info(
                    f"[workflow]   template={best.template.id}  "
                    f"score={best.score:.1f}/{best.max_score:.1f}  "
                    f"conf={best.confidence_label}  env={host_res.environment}"
                )

            result.hosts.append(host_res)

        return result
