"""Autostart file management for kiosk compositors.

Encodes the pi109 lesson: labwc autostart order is critical.
  1. kanshid &                   — start output manager
  2. sleep 3                     — wait for kanshi to disable HDMI-A-2
  3. bash ~/kiosk-launch.sh &    — start browser AFTER output is configured

If Chromium starts before kanshi applies the DSI-only profile, it may render
on HDMI-A-2 (which would be blank since no monitor is connected).
"""
from __future__ import annotations

import re
from dataclasses import dataclass


@dataclass
class AutostartEntry:
    """One entry in a compositor autostart file."""

    key: str
    """Unique identifier used for idempotent replacement, e.g. 'kiosk-browser'."""

    line: str
    """The shell line to write, e.g. 'bash ~/kiosk-launch.sh &'."""

    comment: str = ""
    """Optional inline comment explaining the entry."""

    def render(self) -> str:
        """Render as a single autostart file line."""
        if self.comment:
            return f"{self.line}  # [{self.key}] {self.comment}"
        return f"{self.line}  # [{self.key}]"


def ensure_autostart_entry(content: str, entry: AutostartEntry) -> tuple[str, bool]:
    """Idempotently add or replace an entry in an autostart file.

    Looks for a line containing ``[key]`` marker. If found, replaces it.
    If not, appends it. Returns (new_content, changed).
    """
    marker = f"[{entry.key}]"
    rendered = entry.render()
    lines = content.splitlines(keepends=True)
    for i, line in enumerate(lines):
        if marker in line:
            if line.rstrip("\n") == rendered:
                return content, False  # already correct
            lines[i] = rendered + "\n"
            return "".join(lines), True
    # Not found — append
    sep = "\n" if content and not content.endswith("\n") else ""
    return content + sep + rendered + "\n", True


def generate_labwc_autostart(
    kiosk_script: str = "~/kiosk-launch.sh",
    kanshi_settle_secs: int = 3,
    extra_entries: list[AutostartEntry] | None = None,
) -> str:
    """Generate a complete labwc autostart file for a kiosk deployment.

    Encodes the pi109 ordering: kanshi → sleep → browser.

    Args:
        kiosk_script: Path to the kiosk launch shell script.
        kanshi_settle_secs: Seconds to wait after starting kanshi.
            Pi109 used sleep 3 for the Waveshare 8" panel.
        extra_entries: Additional autostart entries appended at the end.
    """
    lines = [
        "# Generated by redeploy hardware/kiosk — do not edit manually",
        "# Pi109 ordering: kanshi first, then browser after settle time",
        "",
        "kanshid &  # [kanshi] output manager (disables HDMI before browser starts)",
        f"sleep {kanshi_settle_secs}  # [kanshi-settle] wait for kanshi DSI-only profile",
        f"bash {kiosk_script} &  # [kiosk-browser] launch browser in kiosk mode",
    ]
    if extra_entries:
        lines.append("")
        for e in extra_entries:
            lines.append(e.render())
    return "\n".join(lines) + "\n"
