"""Static analysis engine for migration specs.

Scans compiled MigrationSpec + raw markpact blocks for:
- missing local files/paths referenced in steps (src, dst, command, config_file)
- broken command_ref / insert_before references
- docker-compose.yml inconsistencies (missing files, volume paths, build contexts)
- hardcoded absolute paths to external dependencies in commands
- .env / config file references
"""
from __future__ import annotations

import fnmatch
import re
import shlex
import shutil
import subprocess
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any

import yaml

from ..markpact.models import MarkpactDocument
from ..models.plan import MigrationStep
from ..models.spec import MigrationSpec


class IssueSeverity(str, Enum):
    ERROR = "error"
    WARNING = "warning"
    INFO = "info"


@dataclass
class Issue:
    severity: IssueSeverity
    category: str
    step_id: str | None
    message: str
    suggestion: str | None = None
    line: int | None = None


@dataclass
class AnalysisResult:
    issues: list[Issue] = field(default_factory=list)
    passed: bool = True

    def add(self, severity: IssueSeverity, category: str, message: str,
            step_id: str | None = None, suggestion: str | None = None, line: int | None = None) -> None:
        self.issues.append(Issue(severity, category, step_id, message, suggestion, line))
        if severity == IssueSeverity.ERROR:
            self.passed = False

    def errors(self) -> list[Issue]:
        return [i for i in self.issues if i.severity == IssueSeverity.ERROR]

    def warnings(self) -> list[Issue]:
        return [i for i in self.issues if i.severity == IssueSeverity.WARNING]


DEFAULT_REDEPLOYIGNORE = """# .redeployignore — files excluded from deployment sync
# Auto-generated by redeploy. Edit as needed.

# Python
__pycache__/
*.pyc
*.pyo
.venv/
env/
venv/

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Build artifacts
dist/
build/
*.egg-info/
node_modules/
target/

# Version control (already handled by git, but explicit here)
.git/
"""


def ensure_redeployignore(base_dir: Path) -> None:
    """Create .redeployignore with sensible defaults if it doesn't exist."""
    path = base_dir / ".redeployignore"
    if not path.exists():
        path.write_text(DEFAULT_REDEPLOYIGNORE)


class _IgnoreList:
    """Read .gitignore and .redeployignore patterns and test if paths are ignored."""

    def __init__(self, base_dir: Path):
        self.patterns: list[str] = []
        self._load(base_dir / ".gitignore")
        self._load(base_dir / ".redeployignore")

    def _load(self, path: Path) -> None:
        if not path.exists():
            return
        for line in path.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#"):
                self.patterns.append(line)

    def is_ignored(self, rel_path: Path) -> bool:
        """Check if a path relative to base_dir matches any ignore pattern."""
        parts = rel_path.parts
        name = rel_path.name

        for pattern in self.patterns:
            pat = pattern.rstrip("/")
            # Direct filename match
            if fnmatch.fnmatch(name, pat):
                return True
            # Any path component match
            for part in parts:
                if fnmatch.fnmatch(part, pat):
                    return True
            # Directory-depth patterns with slash
            if "/" in pattern:
                pat_parts = pat.split("/")
                # Try matching at each possible depth
                for start in range(len(parts) - len(pat_parts) + 1):
                    match = True
                    for i, pp in enumerate(pat_parts):
                        if not fnmatch.fnmatch(parts[start + i], pp):
                            match = False
                            break
                    if match:
                        return True
        return False


class _Checker:
    def check(self, spec: MigrationSpec, document: MarkpactDocument | None,
              base_dir: Path, result: AnalysisResult) -> None:
        raise NotImplementedError


class _PathChecker(_Checker):
    """Validate local file paths referenced by steps."""

    def check(self, spec, document, base_dir, result):
        ign = _IgnoreList(base_dir)
        for step in spec.extra_steps:
            self._check_field(step, "src", base_dir, result, ign)
            self._check_field(step, "dst", base_dir, result, ign)
            self._check_field(step, "config_file", base_dir, result, ign)
            self._check_env_file(step, base_dir, result)

    def _check_field(self, step: dict, field_name: str, base_dir: Path, result: AnalysisResult, ign: _IgnoreList):
        val = step.get(field_name)
        if not val:
            return
        # Only check local (non-ssh) paths; remote paths often start with ~ or user@host:...
        if re.search(r"^[\w.-]+@", str(val)):
            return
        # dst pointing to remote home (~/) is not a local path to verify
        if field_name == "dst" and str(val).startswith("~/"):
            return
        path = self._resolve(val, base_dir)
        if path and not path.exists():
            # Skip if the missing path matches an ignore pattern
            try:
                rel = path.resolve().relative_to(base_dir.resolve())
                if ign.is_ignored(rel):
                    return
            except ValueError:
                pass
            result.add(
                IssueSeverity.ERROR, "paths",
                f"Step '{step.get('id')}' references missing {field_name}: {val}",
                step.get("id"),
                suggestion=f"Create file/dir or correct path: {path}"
            )

    def _check_env_file(self, step: dict, base_dir: Path, result: AnalysisResult):
        # Some steps may compose env_file indirectly; we also scan raw commands for .env
        pass

    @staticmethod
    def _resolve(val: str, base_dir: Path) -> Path | None:
        val = val.strip()
        if val.startswith("~/"):
            return Path.home() / val[2:]
        if val.startswith("/"):
            return Path(val)
        # relative -> resolve against base_dir
        return base_dir / val


class _CommandPathChecker(_Checker):
    """Scan command strings for hardcoded absolute paths outside the project."""

    EXTERNAL_RE = re.compile(
        r"(?:^|\s)(/home/\w+/[^\s'\"]+|~/[^\s'\"]+)"
    )

    def check(self, spec, document, base_dir, result):
        for step in spec.extra_steps:
            cmd = step.get("command") or ""
            for match in self.EXTERNAL_RE.finditer(cmd):
                path_str = match.group(1)
                # Skip remote target paths (ssh_cmd / inline_script running remotely)
                if path_str.startswith("~/"):
                    continue
                # Ignore paths inside the project tree
                resolved = self._resolve(path_str, base_dir)
                if resolved and self._is_inside(resolved, base_dir):
                    continue
                # Check if exists locally
                if resolved and not resolved.exists():
                    result.add(
                        IssueSeverity.ERROR, "commands",
                        f"Step '{step.get('id')}' command references missing external path: {path_str}",
                        step.get("id"),
                        suggestion="Add rsync/scp step to sync this dependency, or correct the path."
                    )
                else:
                    result.add(
                        IssueSeverity.WARNING, "commands",
                        f"Step '{step.get('id')}' command references external path: {path_str}",
                        step.get("id"),
                        suggestion="Consider adding an explicit sync step for this dependency."
                    )

    @staticmethod
    def _resolve(val: str, base_dir: Path) -> Path | None:
        val = val.strip().rstrip("/")
        if val.startswith("~/"):
            return Path.home() / val[2:]
        if val.startswith("/"):
            return Path(val)
        return base_dir / val

    @staticmethod
    def _is_inside(path: Path, base: Path) -> bool:
        try:
            path.resolve().relative_to(base.resolve())
            return True
        except ValueError:
            return False


class _ReferenceChecker(_Checker):
    """Ensure command_ref and insert_before point to existing things."""

    def check(self, spec, document, base_dir, result):
        from redeploy.steps import StepLibrary
        step_ids = {s.get("id") for s in spec.extra_steps if s.get("id")}
        step_ids |= set(StepLibrary.list())
        ref_ids = set()
        if document:
            for block in document.blocks:
                if block.kind == "ref" and block.ref_id:
                    ref_ids.add(block.ref_id)

        for step in spec.extra_steps:
            sid = step.get("id")
            cref = step.get("command_ref")
            if cref and cref not in ref_ids:
                result.add(
                    IssueSeverity.ERROR, "references",
                    f"Step '{sid}' references unknown command_ref '{cref}'",
                    sid,
                    suggestion=f"Define a ```bash markpact:ref {cref} block or remove command_ref."
                )
            ib = step.get("insert_before")
            if ib and ib not in step_ids:
                result.add(
                    IssueSeverity.WARNING, "references",
                    f"Step '{sid}' insert_before points to unknown step '{ib}'",
                    sid,
                    suggestion="This may be a runtime-generated step; verify the generated plan."
                )


class _ComposeChecker(_Checker):
    """Validate docker-compose files declared in spec or found in project."""

    def check(self, spec, document, base_dir, result):
        ign = _IgnoreList(base_dir)
        compose_files = list(spec.target.compose_files or [])
        # Also try to discover common names if none explicitly declared
        if not compose_files:
            for candidate in ("docker-compose.yml", "docker-compose.yaml", "compose.yml", "compose.yaml"):
                if (base_dir / candidate).exists():
                    compose_files.append(candidate)
                    break

        for cf in compose_files:
            path = base_dir / cf
            if not path.exists():
                result.add(
                    IssueSeverity.ERROR, "compose",
                    f"Declared compose file not found: {cf}",
                    suggestion=f"Create {path} or remove from target.compose_files."
                )
                continue
            self._scan_compose(path, base_dir, result, ign)

    def _scan_compose(self, path: Path, base_dir: Path, result: AnalysisResult, ign: _IgnoreList):
        try:
            data = yaml.safe_load(path.read_text()) or {}
        except Exception as exc:
            result.add(IssueSeverity.ERROR, "compose", f"Cannot parse {path}: {exc}")
            return

        def _skip_ignored(check_path: Path) -> bool:
            try:
                rel = check_path.resolve().relative_to(base_dir.resolve())
                return ign.is_ignored(rel)
            except ValueError:
                return False

        services = data.get("services", {})
        for svc_name, svc in services.items():
            if not isinstance(svc, dict):
                continue
            # build.context
            build = svc.get("build")
            if isinstance(build, dict):
                ctx = build.get("context", ".")
                ctx_path = base_dir / ctx if not ctx.startswith("/") else Path(ctx)
                if not ctx_path.exists():
                    result.add(
                        IssueSeverity.ERROR, "compose",
                        f"Service '{svc_name}' build.context missing: {ctx}",
                        suggestion=f"Create directory {ctx_path} or fix context."
                    )
                dockerfile = build.get("dockerfile")
                if dockerfile:
                    df_path = ctx_path / dockerfile
                    if not df_path.exists() and not _skip_ignored(df_path):
                        result.add(
                            IssueSeverity.ERROR, "compose",
                            f"Service '{svc_name}' Dockerfile missing: {df_path}",
                            suggestion=f"Create {df_path} or correct dockerfile path."
                        )
            # env_file
            env_files = svc.get("env_file", [])
            if isinstance(env_files, str):
                env_files = [env_files]
            for ef in env_files:
                ef_path = base_dir / ef if not str(ef).startswith("/") else Path(ef)
                if not ef_path.exists() and not _skip_ignored(ef_path):
                    result.add(
                        IssueSeverity.WARNING, "compose",
                        f"Service '{svc_name}' env_file missing: {ef}",
                        suggestion=f"Create {ef_path} or remove env_file entry."
                    )
            # volumes
            for vol in svc.get("volumes", []):
                if isinstance(vol, str):
                    if ":" in vol:
                        host_part = vol.split(":", 1)[0]
                        # Skip named volumes and relative paths that exist
                        if host_part.startswith("/"):
                            if not Path(host_part).exists() and not _skip_ignored(Path(host_part)):
                                result.add(
                                    IssueSeverity.WARNING, "compose",
                                    f"Service '{svc_name}' volume host path missing: {host_part}",
                                    suggestion=f"Ensure host path exists before deployment."
                                )
                        elif host_part != "." and "/" in host_part:
                            hp = base_dir / host_part
                            if not hp.exists() and not _skip_ignored(hp):
                                result.add(
                                    IssueSeverity.WARNING, "compose",
                                    f"Service '{svc_name}' relative volume path missing: {hp}",
                                    suggestion=f"Create {hp} or mount as named volume."
                                )


class _DockerBuildChecker(_Checker):
    """Validate docker build commands: Dockerfile exists, context is consistent."""

    DOCKER_BUILD_RE = re.compile(
        r"docker\s+(?:buildx\s+)?build\s+"
    )
    FILE_FLAG_RE = re.compile(r"-f\s+(\S+)|--file[=\s]+(\S+)")
    CONTEXT_RE = re.compile(r"[^\s]+\s+(\S+)$")  # last non-flag argument

    def check(self, spec, document, base_dir, result):
        # Collect all sync destinations for context verification
        sync_dests = set()
        sync_mappings: list[tuple[str, str]] = []  # (remote dst, local src)
        for step in spec.extra_steps:
            sid = step.get("id", "")
            if sid.startswith("sync_"):
                dst = step.get("dst", "")
                src = step.get("src", "")
                if dst:
                    sync_dests.add(dst.rstrip("/"))
                    if src:
                        sync_mappings.append((dst.rstrip("/"), src))

        for step in spec.extra_steps:
            cmd = step.get("command", "")
            if not self.DOCKER_BUILD_RE.search(cmd):
                continue

            sid = step.get("id", "unknown")

            # Extract -f/--file
            dockerfile = None
            for match in self.FILE_FLAG_RE.finditer(cmd):
                dockerfile = match.group(1) or match.group(2)
                break

            # Extract context (last non-flag argument)
            context = "."
            tokens = cmd.split()
            # Remove flags and their values to find context
            i = len(tokens) - 1
            while i > 0:
                token = tokens[i]
                if token.startswith("-"):
                    i -= 1
                    continue
                # Check if previous token is -f or --file
                if i > 0 and tokens[i-1] in ("-f", "--file"):
                    i -= 2
                    continue
                if tokens[i-1].startswith("--file="):
                    i -= 1
                    continue
                context = token
                break
                i -= 1

            # Validate Dockerfile reference
            if dockerfile and not dockerfile.startswith("/") and not dockerfile.startswith("~"):
                # Relative Dockerfile path - check in local base_dir
                df_path = base_dir / dockerfile
                if not df_path.exists():
                    result.add(
                        IssueSeverity.ERROR, "docker_build",
                        f"Step '{sid}' docker build references missing Dockerfile: {dockerfile}",
                        sid,
                        suggestion=f"Create {df_path} or use standard 'Dockerfile' name."
                    )
                elif dockerfile not in ("Dockerfile", "dockerfile", "Dockerfile.prod", "Dockerfile.dev"):
                    # Non-standard Dockerfile name - info
                    result.add(
                        IssueSeverity.WARNING, "docker_build",
                        f"Step '{sid}' uses non-standard Dockerfile name: {dockerfile}",
                        sid,
                        suggestion="Consider using standard 'Dockerfile' with multi-arch support."
                    )

            # Check context path consistency with sync destinations
            if context.startswith("~/"):
                # Remote path - check if any sync destination matches
                context_clean = context.rstrip("/")
                context_remote = context_clean[2:]  # e.g., "c2004/oqlos/cql"
                sync_remote_paths = {
                    d[2:].rstrip("/") for d in sync_dests if d.startswith("~/")
                }
                # Context should be exactly a sync dest or a subdirectory of one
                matched = any(
                    context_remote == sp or context_remote.startswith(sp + "/")
                    for sp in sync_remote_paths
                )
                if not matched and sync_dests:
                    result.add(
                        IssueSeverity.WARNING, "docker_build",
                        f"Step '{sid}' docker build uses remote context '{context}' that doesn't match any sync destination",
                        sid,
                        suggestion=f"Sync destinations: {', '.join(sorted(sync_dests))} — verify context path."
                    )

                # If context maps to a synced local dir, verify Dockerfile exists locally there too.
                if dockerfile and matched:
                    local_src = self._match_local_src(sync_mappings, context_clean)
                    if local_src:
                        local_df = self._resolve_local_dockerfile(local_src, dockerfile, base_dir)
                        if local_df is not None and not local_df.exists():
                            result.add(
                                IssueSeverity.ERROR,
                                "docker_build",
                                f"Step '{sid}' Dockerfile '{dockerfile}' not found in synced local source '{local_src}'",
                                sid,
                                suggestion=f"Ensure {dockerfile} exists under {local_src} before sync/build.",
                            )

    @staticmethod
    def _match_local_src(sync_mappings: list[tuple[str, str]], remote_context: str) -> str | None:
        for remote_dst, local_src in sync_mappings:
            if not remote_dst.startswith("~/"):
                continue
            dst_clean = remote_dst.rstrip("/")
            if remote_context == dst_clean or remote_context.startswith(dst_clean + "/"):
                return local_src
        return None

    @staticmethod
    def _resolve_local_dockerfile(local_src: str, dockerfile: str, base_dir: Path) -> Path | None:
        src = local_src.rstrip("/")
        src_path = Path(src)
        if not src_path.is_absolute():
            src_path = (base_dir / src_path).resolve()
        if dockerfile.startswith("/"):
            return Path(dockerfile)
        return src_path / dockerfile


class _CommandRefChecker(_Checker):
    """Validate command_ref references for nested markdown/script dependencies."""

    def check(self, spec, document, base_dir, result):
        from ..markpact.parser import extract_script_by_ref, extract_script_from_markdown

        in_doc_refs: set[str] = set()
        if document:
            for block in document.blocks:
                if block.kind == "ref" and block.ref_id:
                    in_doc_refs.add(block.ref_id)

        for step in spec.extra_steps:
            sid = step.get("id")
            cref = step.get("command_ref")
            if not cref:
                continue

            if "#" in cref:
                file_part, ref_id = cref.split("#", 1)
                if file_part:
                    file_path = self._resolve(file_part, base_dir)
                    if not file_path.exists():
                        result.add(
                            IssueSeverity.ERROR,
                            "command_ref",
                            f"Step '{sid}' command_ref file missing: {file_part}",
                            sid,
                            suggestion=f"Create or fix path: {file_path}",
                        )
                        continue
                    text = file_path.read_text(encoding="utf-8", errors="replace")
                    if not (
                        extract_script_by_ref(text, ref_id, language="bash")
                        or extract_script_from_markdown(text, ref_id, language="bash")
                    ):
                        result.add(
                            IssueSeverity.ERROR,
                            "command_ref",
                            f"Step '{sid}' command_ref '#{ref_id}' not found in {file_part}",
                            sid,
                            suggestion="Add a matching markpact:ref bash block or section heading script.",
                        )
                else:
                    if document and ref_id not in in_doc_refs:
                        result.add(
                            IssueSeverity.WARNING,
                            "command_ref",
                            f"Step '{sid}' command_ref '#{ref_id}' not found as markpact:ref in current spec",
                            sid,
                            suggestion="If this is a heading-based script, keep as-is; otherwise add markpact:ref block.",
                        )
                continue

            # Simple ref id in current markdown doc.
            if document and cref not in in_doc_refs:
                result.add(
                    IssueSeverity.WARNING,
                    "command_ref",
                    f"Step '{sid}' references unknown command_ref '{cref}'",
                    sid,
                    suggestion="Define a matching markpact:ref block in this spec.",
                )

    @staticmethod
    def _resolve(val: str, base_dir: Path) -> Path:
        val = val.strip()
        if val.startswith("~/"):
            return Path.home() / val[2:]
        if val.startswith("/"):
            return Path(val)
        return base_dir / val


class _EnvFileChecker(_Checker):
    """Check that .env referenced by target.env_file exists."""

    def check(self, spec, document, base_dir, result):
        ef = spec.target.env_file or spec.source.env_file
        if ef:
            path = base_dir / ef if not ef.startswith("/") else Path(ef)
            if not path.exists():
                result.add(
                    IssueSeverity.ERROR, "env",
                    f"env_file not found: {ef}",
                    suggestion=f"Create {path} or correct env_file path."
                )


class _BinaryChecker(_Checker):
    """Warn if commands reference binaries not available locally (best-effort)."""

    def check(self, spec, document, base_dir, result):
        for step in spec.extra_steps:
            action = str(step.get("action") or "")
            if action in {"ensure_kanshi_profile"}:
                # This action uses declarative profile syntax, not shell commands.
                continue
            cmd = step.get("command") or ""
            for binary in self._extract_binaries(cmd):
                if not self._which(binary):
                    result.add(
                        IssueSeverity.WARNING,
                        "binaries",
                        f"Step '{step.get('id')}' command uses binary not found locally: '{binary}'",
                        step.get("id"),
                        suggestion=f"Install '{binary}' locally for lint parity, or ignore if it exists only on remote host.",
                    )

    @staticmethod
    def _extract_binaries(cmd: str) -> list[str]:
        wrappers = {"sudo", "env", "command", "nohup", "time", "exec"}
        keywords = {
            "if", "then", "else", "fi", "for", "do", "done", "while", "case", "esac",
            "function", "in", "until", "select", "echo", "true", "false", "test", "[", "[[",
        }
        separators = {"&&", "||", "|", ";", "(" , ")", "{" , "}"}

        try:
            tokens = shlex.split(cmd, posix=True)
        except ValueError:
            # Keep lint robust on malformed shell snippets.
            tokens = cmd.split()

        out: list[str] = []
        expect_cmd = True
        i = 0
        while i < len(tokens):
            tok = tokens[i]

            if tok in separators:
                expect_cmd = True
                i += 1
                continue

            if expect_cmd:
                if tok in keywords or tok.startswith("$"):
                    if tok == "for":
                        # `for <var> in ...` — skip variable token.
                        i += 1
                    i += 1
                    expect_cmd = False
                    continue
                if "=" in tok and not tok.startswith("--") and "/" not in tok:
                    # shell assignment prefix: FOO=bar cmd
                    i += 1
                    continue
                if tok in wrappers:
                    i += 1
                    continue
                if re.match(r"^[a-zA-Z_][a-zA-Z0-9_.-]*$", tok) and len(tok) > 1:
                    out.append(tok)
                expect_cmd = False
            i += 1
        return out

    @staticmethod
    def _which(cmd: str) -> bool:
        return shutil.which(cmd) is not None


class SpecAnalyzer:
    """Run static checks against a compiled MigrationSpec (and optional raw MarkpactDocument)."""

    DEFAULT_CHECKERS: list[_Checker] = [
        _PathChecker(),
        _CommandPathChecker(),
        _DockerBuildChecker(),
        _CommandRefChecker(),
        _ReferenceChecker(),
        _ComposeChecker(),
        _EnvFileChecker(),
        _BinaryChecker(),
    ]

    def __init__(self, base_dir: Path | None = None,
                 checkers: list[_Checker] | None = None,
                 auto_create_redeployignore: bool = True):
        self.base_dir = base_dir or Path.cwd()
        self.checkers = checkers or list(self.DEFAULT_CHECKERS)
        self.auto_create_redeployignore = auto_create_redeployignore

    def analyze(self, spec: MigrationSpec,
                document: MarkpactDocument | None = None) -> AnalysisResult:
        result = AnalysisResult()
        for checker in self.checkers:
            checker.check(spec, document, self.base_dir, result)
        return result

    def analyze_file(self, spec_path: Path) -> tuple[MigrationSpec | None, AnalysisResult]:
        """Load spec from file (YAML or markpact) and analyze."""
        from ..markpact.parser import parse_markpact_file
        from ..markpact.compiler import compile_markpact_document, MarkpactCompileError
        from ..models.spec import MigrationSpec as MS

        # Ensure .redeployignore exists with sensible defaults
        if self.auto_create_redeployignore:
            ensure_redeployignore(self.base_dir)

        document = None
        spec = None
        result = AnalysisResult()

        # Try markpact first
        if spec_path.suffix == ".md":
            try:
                document = parse_markpact_file(spec_path)
                spec = compile_markpact_document(document)
            except MarkpactCompileError as exc:
                result.add(IssueSeverity.ERROR, "compile", str(exc))
                return None, result
            except Exception as exc:
                result.add(IssueSeverity.ERROR, "compile", f"Failed to parse markpact: {exc}")
                return None, result
        else:
            try:
                spec = MS.from_file(spec_path)
            except Exception as exc:
                result.add(IssueSeverity.ERROR, "load", f"Failed to load spec: {exc}")
                return None, result

        if spec:
            result = self.analyze(spec, document)
        return spec, result
